name: Build ANIMORA APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build ANIMORA
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Check Flutter
        run: flutter --version

      - name: Extract ANIMORA ZIP
        run: |
          rm -rf extracted
          mkdir extracted
          unzip -q ANIMORA_flutter_starter.zip -d extracted

          PROJECT_DIR=$(dirname "$(find extracted -name pubspec.yaml -print -quit)")

          if [ -z "$PROJECT_DIR" ]; then
            echo "ERROR: pubspec.yaml not found"
            exit 1
          fi

          echo "Found project:"
          echo "$PROJECT_DIR"

          echo "PROJECT_DIR=$PROJECT_DIR" >> "$GITHUB_ENV"

      - name: Create clean Flutter Android project
        run: |
          rm -rf animora_build

          flutter create \
            --platforms=android \
            --org com.animora \
            --project-name animora \
            animora_build

      - name: Copy ANIMORA files
        run: |
          cp "$PROJECT_DIR/pubspec.yaml" animora_build/pubspec.yaml

          rm -rf animora_build/lib
          cp -r "$PROJECT_DIR/lib" animora_build/lib

          rm -rf animora_build/test

          if [ -f "$PROJECT_DIR/README.md" ]; then
            cp "$PROJECT_DIR/README.md" animora_build/README.md
          fi

      - name: Get dependencies
        working-directory: animora_build
        run: |
          flutter clean
          flutter pub get

      - name: Build ANIMORA APK
        working-directory: animora_build
        run: |
          flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ANIMORA-APK
          path: animora_build/build/app/outputs/flutter-apk/app-release.apk
          if-no-files-found: error
